version: '3'
services:
  mysqldb:
    image: mysql:5.7.19
    container_name: banco
    ports:
      - "3306:3306"
    command:  --init-file /var/lib/mysql/database_schema.sql
    volumes:
      - ./database_schema.sql:/var/lib/mysql/database_schema.sql
      - /home/tviana/Documentos/Projeto/banco:/var/lib/mysql
      - /home/tviana/Documentos/Projeto/:/docker-entrypoint-initdb.d/:ro
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: note
        MYSQL_USER: notes-api
        MYSQL_PASSWORD: notes
    networks:
      rede:
        ipv4_address: 10.5.0.5
        
  nodejs:
    build:
      context: .
      dockerfile: dockernodejs
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    command: node server.js
    networks:
      rede:
        ipv4_address: 10.5.0.3
    depends_on:
      - mysqldb

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      rede:
        ipv4_address: 10.5.0.4     

networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
